steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--build-arg'
      - 'ENTRYPOINT=${_ENTRYPOINT}'
      - '--build-arg'
      - 'RUNTIME_REF=${_RUNTIME_REF}'
      - '-t'
      - '${_IMAGE}'
      - '.'
images:
  - '${_IMAGE}'
